Fix: typo & grammar
Bricklou/launcher-tutorials pull request #7
Opened 2024-01-15 17:28 UTC by cakihorse

2024-01-16 06:42 UTC, Bricklou requested changes

2024-01-16 06:42 UTC, Bricklou commented on pages/swing-launcher/Get-Started.mdx
> +S'il vous plait, ayez une bonne connaissance de votre sujet (java, swing) pour ne pas être peiné dans votre projet.
"ne pas être peiné" ?

2024-01-16 06:42 UTC, Bricklou commented on pages/swing-launcher/Get-Started.mdx
> + - Ouvrez le projet avec l'ide que vous souhaitez (Intelij Idea est fortement recommandé).
Intel**l**ij IDEA

2024-01-16 06:42 UTC, Bricklou commented on pages/swing-launcher/Launcher.java.mdx
> +Cette class permet de lancer un client minecraft en utilisant FlowUpdater. Vous pouvez trouver plus d'informations à ce propos ici: [FlowUpdater](../../flow-updater)
Class**e**

2024-01-16 06:42 UTC, Bricklou commented on pages/swing-launcher/Launcher.java.mdx
> +        Avec `"noFramework.getAdditionalVmArgs().add("eheh i'm a Vm argument");`,vous pouvez ajouter un argument à la jvm, mais vous n'avez pas enormément de possibilité d'utilisation pour un client
Généra**l**ement 
~~la ram~~ : l'allocation en mémoire

2024-01-29 16:30 UTC, cakihorse commented on pages/swing-launcher/Launcher.java.mdx
> +        Avec `"noFramework.getAdditionalVmArgs().add("eheh i'm a Vm argument");`,vous pouvez ajouter un argument à la jvm, mais vous n'avez pas enormément de possibilité d'utilisation pour un client
Merci :)
Je corrige ça de suite !

2024-01-30 07:28 UTC, Bricklou commented on pages/swing-launcher/Main.java.mdx
> +Cette classe extends Jframe, donc nous pouvons directement utiliser la fonction Main() pour mettre en place la fenêtre.
"étends la classe JFrame"

2024-04-13 18:52 UTC, Bricklou approved these changes

2024-04-13 19:01 UTC, merged